language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: V5OS/YbOX0uZUSYMBkgbTyFAwAxDEZdTD5LnFYYX9EYZZca8WjAt8QOrNH4OBtmAJmnU8/uvaw9T6/C5QKEDTqfGypaKZb1VSHZ7TfKkOkTQyi7D28Iw4XX0ZFs3oY1vcGfQrY+ZL84HILXCpS9GtMbJQ69MOaw3PR8R6IKG8qA=
  - secure: JsQHWecX4unJA/d612DM4xcpENveaIxYAIB2g4bXJKq8ZXgbev1/q4Sxh0Dv57V2WBwD//V9i+RXoMlp+ia7yAjAK4Th6BDFc+HCmgdUcAmS6RcJ/Awmg9WNZTRHsrUYgZstJTFuE4jjeruJKKd/AKx+NZ9uCoXjpLxNbFXyvjM=
  - secure: e6Jiw6Yk/wI2h9szq+Vv/xUuZP4ut+dAPf27cUJ7LSTpVa83nMxqLQ0QcN/GIKsX8W7YKTTkkrsY/ScpV11SaHNmXZsqUVXBxLihGLcrOpsUvy5g61IqXAC8PhOX4CBZuHxw5fw+CIQSlNoCML9Dg9uy9a4mHM6RoaqSbp1r5Ss=
